[package]
name = "time-traveler"
description = "A lightweight crate for converting between chrono and hifitime durations and datetimes."
version = "0.1.0"
authors = ["Philip Linden <lindenphilipj@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.38"
hifitime = "4.0.0-alpha"
